[tool.ruff]
line-length = 120

[tool.coverage.run]
omit = [
    "eventdetector_ts/plotter/*",
    "eventdetector_ts/prediction/*",
    "eventdetector_ts/metamodel/*",
    "eventdetector_ts/optimization/event_extraction_pipeline.py",
    "eventdetector_ts/models/models_trainer.py"
]
source = ["eventdetector_ts"]

[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

[project]
name = "eventdetector_ts"
version = "1.1.0"
description = "This package, EventDetector, introduces a groundbreaking universal event detection method for multivariate time series data. Unlike traditional deep-learning supervised methods, our approach is regression-based, requiring only reference events instead of labeled datasets. It incorporates a robust stacked ensemble learning metamodel, leveraging diverse deep learning models, from Feed-Forward Neural Networks to advanced architectures like Transformers. The ensemble ensures greater resilience and accuracy by mitigating individual model biases. The package facilitates practical implementation of our method, providing comprehensive support for event detection in time series. Mathematically proven to be universal, our method excels in detecting various events, such as change points, frauds, anomalies, and physical occurrences, with remarkable precision. Empirical validations showcase its superior performance, particularly for rare events and imbalanced datasets across diverse domains."
keywords = [
    "Universal Event Detection",
    "Multivariate Time Series",
    "Regression-based",
    "Stacked Ensemble Learning",
    "Deep Learning Models",
    "Feed-Forward Neural Networks",
    "Transformers",
    "Event Detection Package",
    "Rare Events",
    "Imbalanced Datasets",
    "Anomaly Detection",
    "Change Point Detection",
    "Fraud Detection",
    "Empirical Validations"
]
authors = [
    { name = "Menouar Azib", email = "menouar.azib@akkodis.com" }
]

maintainers = [
    { name = "Menouar Azib", email = "menouar.azib@akkodis.com" }
]
requires-python = ">=3.9"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3", "Operating System :: OS Independent"]

dependencies = [
    "joblib",
    "matplotlib",
    "numpy",
    "pandas",
    "python_dateutil",
    "scikit_learn",
    "scipy",
    "seaborn",
    "sympy",
    "colorlog",
    "pydot",
    "pyqt5",
    "tqdm"
]

[project.urls]
"Homepage" = "https://github.com/menouarazib/eventdetector"
"Bug Tracker" = "https://github.com/menouarazib/eventdetector/issues"